name: tap1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2

  # Storage / State
  shared_preferences: ^2.5.4

  # Location
  geolocator: ^10.1.0

  # Firebase
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_analytics: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/icons.png"

flutter:
  uses-material-design: true
